
var BLOCKLY_TOOLBOX_XML = BLOCKLY_TOOLBOX_XML || Object.create(null);

/* BEGINNING BLOCKLY_TOOLBOX_XML ASSIGNMENT. DO NOT EDIT. USE BLOCKLY DEVTOOLS. */
BLOCKLY_TOOLBOX_XML['standard'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="Environment indices" colour="#d31900">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="Environment constants" colour="#ff8500">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="Environment variables" colour="#ffdf00">'
+   '<block type="env_variables"></block>'
+   '<block type="env_variables_1d"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="Environment functions" colour="#b1dc57">'
+   '<block type="distance"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="degree2radian"></block>'
+   '<block type="radian2degree"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="find_closest_robot"></block>'
+   '<block type="ball_is_own_goal"></block>'
+   '<block type="ball_is_own_penalty"></block>'
+   '<block type="ball_is_own_field"></block>'
+   '<block type="ball_is_opp_goal"></block>'
+   '<block type="ball_is_opp_penalty"></block>'
+   '<block type="ball_is_opp_field"></block>'
+   '<block type="ball_is_gk_zone"></block>'
+   '<block type="ball_is_d1_zone"></block>'
+   '<block type="ball_is_d2_zone"></block>'
+   '<block type="ball_is_f1_zone"></block>'
+   '<block type="ball_is_f2_zone"></block>'
+   '<block type="is_state_default"></block>'
+   '<block type="is_state_goalkick"></block>'
+   '<block type="is_state_cornerkick"></block>'
+   '<block type="is_state_kickoff"></block>'
+   '<block type="is_state_penaltykick"></block>'
+   '<block type="is_closest_to_ball"></block>'
+   '<block type="is_close_to_ball"></block>'
+   '<block type="has_ball_possession"></block>'
+   '<block type="is_gk_in_goalcenter"></block>'
+   '<block type="robot_in_front_of_ball"></block>'
+   '<block type="printconsole">'
+     '<mutation divisor_input="true"></mutation>'
+   '</block>'
+ '</category>'
+ '<category name="Environment actions" colour="#04862c">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_right"></block>'
+   '<block type="turn_left"></block>'
+   '<block type="kick"></block>'
+   '<block type="manual_control"></block>'
+   '<block type="jump"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="defend_ball"></block>'
+   '<block type="is_gk_save_possible"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="pass_to_robot"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="is_cross_to_possible"></block>'
+   '<block type="cross_to_robot"></block>'
+   '<block type="is_cross_to_robot_possible"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="#0097bc">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+   '<block type="logic_operation"></block>'
+   '<block type="logic_negate"></block>'
+   '<block type="logic_boolean"></block>'
+   '<block type="logic_null" disabled="true"></block>'
+   '<block type="logic_ternary"></block>'
+ '</category>'
+ '<category name="Loops" colour="#0052be">'
+   '<block type="controls_repeat_ext">'
+     '<value name="TIMES">'
+       '<shadow type="math_number">'
+         '<field name="NUM">10</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="controls_repeat" disabled="true"></block>'
+   '<block type="controls_whileUntil"></block>'
+   '<block type="controls_for">'
+     '<value name="FROM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="TO">'
+       '<shadow type="math_number">'
+         '<field name="NUM">10</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="BY">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="controls_forEach"></block>'
+   '<block type="controls_flow_statements"></block>'
+ '</category>'
+ '<category name="Math" colour="#25286f">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_single">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">9</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_constant"></block>'
+   '<block type="math_number_property">'
+     '<value name="NUMBER_TO_CHECK">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_round">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">3.1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_on_list"></block>'
+   '<block type="math_modulo">'
+     '<value name="DIVIDEND">'
+       '<shadow type="math_number">'
+         '<field name="NUM">64</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="DIVISOR">'
+       '<shadow type="math_number">'
+         '<field name="NUM">10</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_constrain">'
+     '<value name="VALUE">'
+       '<shadow type="math_number">'
+         '<field name="NUM">50</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="LOW">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="HIGH">'
+       '<shadow type="math_number">'
+         '<field name="NUM">100</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_random_int">'
+     '<value name="FROM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="TO">'
+       '<shadow type="math_number">'
+         '<field name="NUM">100</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_random_float"></block>'
+ '</category>'
+ '<category name="Lists" colour="#99138e">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_repeat">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">5</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="lists_length"></block>'
+   '<block type="lists_isEmpty"></block>'
+   '<block type="lists_indexOf">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+   '<block type="lists_setIndex">'
+     '<value name="LIST">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+   '<block type="lists_getSublist">'
+     '<value name="LIST">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+   '<block type="lists_split">'
+     '<value name="DELIM">'
+       '<shadow type="text">'
+         '<field name="TEXT">,</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="lists_sort"></block>'
+   '<block type="lists_reverse"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Variables" colour="#dd056a" custom="VARIABLE"></category>'
+ '<category name="Functions" colour="#000000" custom="PROCEDURE"></category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-1'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="go_forward"></block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-2'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="jump"></block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-3'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="kick"></block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-4'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="go_to"></block>'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-5'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="go_to"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+ '<sep></sep>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-6'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_right"></block>'
+   '<block type="turn_left"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-7'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_right"></block>'
+   '<block type="turn_left"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#917f00">'
+   '<block type="robot_variables"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-8'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_right"></block>'
+   '<block type="turn_left"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="looking_to_target"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-9'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_right"></block>'
+   '<block type="turn_left"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="looking_to_ball"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-level-10'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_right"></block>'
+   '<block type="turn_left"></block>'
+   '<block type="kick"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="looking_to_goal"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-1'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_forward"></block>'
+   '<block type="go_backward"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-2'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-3'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-4'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="looking_to_goal"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-5'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-6'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-7'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-8'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-9'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['intermediate-level-10'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="jump_right_high"></block>'
+   '<block type="jump_right_low"></block>'
+   '<block type="jump_center_high"></block>'
+   '<block type="jump_center_low"></block>'
+   '<block type="jump_left_high"></block>'
+   '<block type="jump_left_low"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-1'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-2'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="opponent_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="robot_to_variables"></block>'
+   '<block type="target_variables"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+   '<block type="looking_to_target"></block>'
+   '<block type="looking_to_goal"></block>'
+   '<block type="looking_to_ball"></block>'
+   '<block type="looking_to_robot"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-3'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-4'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-5'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-6'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-7'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-8'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-9'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['advanced-level-10'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+ '<category name="AI Soccer indices" colour="#00541a">'
+   '<block type="env_coordinates_index"></block>'
+   '<block type="env_robot_index"></block>'
+ '</category>'
+ '<category name="AI Soccer actions" colour="#e04631">'
+   '<block type="stop"></block>'
+   '<block type="go_to"></block>'
+   '<block type="turn_to"></block>'
+   '<block type="pass_to"></block>'
+   '<block type="cross_to"></block>'
+   '<block type="shoot_to"></block>'
+   '<block type="kick"></block>'
+   '<block type="kick_control"></block>'
+ '</category>'
+ '<category name="AI Soccer constants" colour="#566b2b">'
+   '<block type="env_constant_index"></block>'
+   '<block type="env_constant_noindex"></block>'
+ '</category>'
+ '<category name="AI Soccer Variables" colour="#944d00">'
+   '<block type="robot_variables"></block>'
+   '<block type="ball_variables"></block>'
+   '<block type="target_variables"></block>'
+   '<block type="env_variables_2d"></block>'
+ '</category>'
+ '<category name="AI Soccer functions" colour="#944d00">'
+   '<block type="has_ball_possession"></block>'
+   '<block type="predict_ball"></block>'
+   '<block type="relative_distance"></block>'
+   '<block type="distance"></block>'
+ '</category>'
+ '<sep></sep>'
+ '<category name="Logic" colour="210">'
+   '<block type="controls_if"></block>'
+   '<block type="logic_compare"></block>'
+ '</category>'
+ '<category name="Math" colour="230">'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+   '<block type="math_arithmetic">'
+     '<value name="A">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+     '<value name="B">'
+       '<shadow type="math_number">'
+         '<field name="NUM">1</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+   '<block type="math_trig">'
+     '<value name="NUM">'
+       '<shadow type="math_number">'
+         '<field name="NUM">0</field>'
+       '</shadow>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '<category name="Variables" colour="310" custom="VARIABLE"></category>'
+ '<category name="Lists" colour="260">'
+   '<block type="lists_create_with">'
+     '<mutation items="0"></mutation>'
+   '</block>'
+   '<block type="lists_create_with"></block>'
+   '<block type="lists_getIndex">'
+     '<value name="VALUE">'
+       '<block type="variables_get">'
+         '<field name="VAR">list</field>'
+       '</block>'
+     '</value>'
+   '</block>'
+ '</category>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-1'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
// +   '<block type="reward_types"></block>'
// +   '<block type="num_layers"></block>'
// +   '<block type="hidden_dim"></block>'
// +   '<block type="math_number">'
// +     '<field name="NUM">1</field>'
// +   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-2'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="reward_types"></block>'
// +   '<block type="num_layers"></block>'
// +   '<block type="hidden_dim"></block>'
// +   '<block type="math_number">'
// +     '<field name="NUM">1</field>'
// +   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-3'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="state_types"></block>'
// +   '<block type="num_layers"></block>'
// +   '<block type="hidden_dim"></block>'
// +   '<block type="math_number">'
// +     '<field name="NUM">1</field>'
// +   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-4'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="action_types"></block>'
// +   '<block type="num_layers"></block>'
// +   '<block type="hidden_dim"></block>'
// +   '<block type="math_number">'
// +     '<field name="NUM">1</field>'
// +   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-5'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="reward_types"></block>'
// +   '<block type="num_layers"></block>'
// +   '<block type="hidden_dim"></block>'
// +   '<block type="math_number">'
// +     '<field name="NUM">1</field>'
// +   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-6'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="num_layers"></block>'
+   '<block type="hidden_dim"></block>'
+   '<block type="math_number">'
+     '<field name="NUM">1</field>'
+   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-7'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="ddpg_batch_size"></block>'
+   '<block type="num_layers"></block>'
+   '<block type="hidden_dim"></block>'
+   '<block type="math_number">'
+     '<field name="NUM">64</field>'
+   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-8'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="ddpg_dec_exploration"></block>'
+   '<block type="num_layers"></block>'
+   '<block type="hidden_dim"></block>'
+   '<block type="math_number">'
+     '<field name="NUM">20000</field>'
+   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-9'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="ddpg_gamma"></block>'
+   '<block type="ddpg_dec_exploration"></block>'
+   '<block type="num_layers"></block>'
+   '<block type="hidden_dim"></block>'
+   '<block type="math_number">'
+     '<field name="NUM">0.99</field>'
+   '</block>'
+ '</xml>';

BLOCKLY_TOOLBOX_XML['beginner-rl-level-10'] =
// From XML string/file, replace ^\s?(\s*)?(<.*>)$ with \+$1'$2'
// Tweak first and last line.
'<xml xmlns="https://developers.google.com/blockly/xml">'
+   '<block type="train"></block>'
+   '<block type="play"></block>'
+   '<block type="action_sets"></block>'
+   '<block type="dqn_buffer_size"></block>'
+   '<block type="dqn_dec_exploration"></block>'
+   '<block type="num_layers"></block>'
+   '<block type="hidden_dim"></block>'
+   '<block type="math_number">'
+     '<field name="NUM">5000</field>'
+   '</block>'
+ '</xml>';
/* END BLOCKLY_TOOLBOX_XML ASSIGNMENT. DO NOT EDIT. */
