var SINGLE_PARAMETERS = 
'{'
+ '  "dqn_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 32,'
+ '    "buffer_size": 50000,'
+ '    "lr": 0.001,'
+ '    "epsilon_steps": 0.001,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "ddpg_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 32,'
+ '    "buffer_size": 50000,'
+ '    "lr": 0.001,'
+ '    "exploration_noise": 0.2,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "agent_parameters": {'
+ '    "hidden_dim": 64'
+ '  },'
+ '  "sim_parameters": {'
+ '    "frame_skip": 4,'
+ '    "robot": [false, false, false, false, true]'
+ '  }'
+ '}';

var MULTI_PARAMETERS = 
'{'
+ '  "iql_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 32,'
+ '    "buffer_size": 50000,'
+ '    "lr": 0.001,'
+ '    "epsilon_steps": 0.001,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "qmix_parameters": {'
+ '    "gamma": 0.99,'
+ '    "batch_size": 32,'
+ '    "buffer_size": 50000,'
+ '    "lr": 0.001,'
+ '    "exploration_noise": 0.2,'
+ '    "grad_norm_clip": 10'
+ '  },'
+ '  "agent_parameters": {'
+ '    "hidden_dim": 64'
+ '  },'
+ '  "sim_parameters": {'
+ '    "frame_skip": 4,'
+ '    "robot": [true, true, true, true, true]'
+ '  }'
+ '}';